"""
PDF exporter — native PDF generation from raw byte streams
complying with the PDF-1.4 specification without external dependencies.
Optimized for A4 portrait layout with high-end typography and styling.
"""

from typing import List, Dict, Any
from datetime import datetime, timezone
from app.planner.models import MigrationPlan
from app.discovery.inventory import get_inventory


class PDFDocument:
    """Helper to assemble a PDF structure and calculate offsets for the cross-reference table."""

    def __init__(self) -> None:
        self.objects: List[bytes] = []

    def add_object(self, obj_bytes: bytes) -> int:
        """Add an object's payload to the list and return its 1-indexed object ID."""
        self.objects.append(obj_bytes)
        return len(self.objects)

    def serialize(self) -> bytes:
        """Compile the objects, cross-reference table, and trailer into PDF bytes."""
        out = bytearray()
        out.extend(b"%PDF-1.4\n")

        offsets = {}
        # Serialize objects
        for idx, obj in enumerate(self.objects):
            obj_id = idx + 1
            offsets[obj_id] = len(out)
            out.extend(f"{obj_id} 0 obj\n".encode("utf-8"))
            out.extend(obj)
            out.extend(b"\nendobj\n")

        # Start of cross-reference table
        xref_start = len(out)
        out.extend(b"xref\n")
        # 0 object + active objects
        out.extend(f"0 {len(self.objects) + 1}\n".encode("utf-8"))
        # First entry: free object list head
        out.extend(b"0000000000 65535 f \n")
        
        # Write offsets for each object
        for obj_id in range(1, len(self.objects) + 1):
            offset = offsets[obj_id]
            out.extend(f"{offset:010d} 00000 n \n".encode("utf-8"))

        out.extend(b"trailer\n")
        out.extend(f"<< /Size {len(self.objects) + 1} /Root 1 0 R >>\n".encode("utf-8"))
        out.extend(b"startxref\n")
        out.extend(f"{xref_start}\n".encode("utf-8"))
        out.extend(b"%%EOF\n")

        return bytes(out)


def escape_pdf_str(text: str) -> str:
    """Escape parentheses and backslashes for PDF string fields."""
    return (
        str(text)
        .replace("\\", "\\\\")
        .replace("(", "\\(")
        .replace(")", "\\)")
    )


class PDFPageWriter:
    """Helper to write PDF content stream commands for a single A4 page (595 x 842 pt)."""

    def __init__(self, page_num: int, total_pages: int = 6, timestamp: str = "") -> None:
        self.page_num = page_num
        self.total_pages = total_pages
        self.timestamp = timestamp or datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        self.width = 595
        self.height = 842
        self.commands: List[str] = []

        # Standard header/footer for all pages except cover page (page 1)
        if self.page_num > 1:
            self.draw_header_footer()

    def add_cmd(self, cmd: str) -> None:
        self.commands.append(cmd)

    def draw_line(self, x1: float, y1: float, x2: float, y2: float, color=(0.8, 0.8, 0.8), width=0.5) -> None:
        self.add_cmd(f"{width} w")
        self.add_cmd(f"{color[0]} {color[1]} {color[2]} RG")
        self.add_cmd(f"{x1} {y1} m {x2} {y2} l s")

    def draw_rect(self, x: float, y: float, w: float, h: float, fill_color=None, stroke_color=None, border_width=0.5) -> None:
        if fill_color:
            self.add_cmd(f"{fill_color[0]} {fill_color[1]} {fill_color[2]} rg")
        if stroke_color:
            self.add_cmd(f"{border_width} w")
            self.add_cmd(f"{stroke_color[0]} {stroke_color[1]} {stroke_color[2]} RG")
        
        self.add_cmd(f"{x} {y} {w} {h} re")
        if fill_color and stroke_color:
            self.add_cmd("B")
        elif fill_color:
            self.add_cmd("f")
        elif stroke_color:
            self.add_cmd("s")

    def draw_text(self, text: str, x: float, y: float, font="/F1", size=10, color=(0.1, 0.1, 0.1)) -> None:
        self.add_cmd("BT")
        self.add_cmd(f"{color[0]} {color[1]} {color[2]} rg")
        self.add_cmd(f"{font} {size} Tf")
        self.add_cmd(f"{x} {y} Td")
        self.add_cmd(f"({escape_pdf_str(text)}) Tj")
        self.add_cmd("ET")

    def draw_header_footer(self) -> None:
        # Running Header
        self.draw_text("Enterprise PQC Migration Plan", 40, 805, font="/F2", size=8, color=(0.4, 0.4, 0.4))
        self.draw_text("CONFIDENTIAL", 500, 805, font="/F2", size=8, color=(0.8, 0.2, 0.2))
        self.draw_line(40, 797, 555, 797, color=(0.85, 0.85, 0.85), width=0.5)

        # Running Footer
        self.draw_line(40, 48, 555, 48, color=(0.85, 0.85, 0.85), width=0.5)
        self.draw_text("Generated by Enterprise PQC Migration Engine", 40, 32, font="/F1", size=8, color=(0.5, 0.5, 0.5))
        self.draw_text(self.timestamp, 240, 32, font="/F1", size=7.5, color=(0.6, 0.6, 0.6))
        self.draw_text(f"Page {self.page_num} of {self.total_pages}", 505, 32, font="/F1", size=8, color=(0.5, 0.5, 0.5))

    def render(self) -> str:
        return "\n".join(self.commands)


def export_plan_to_pdf(plan: MigrationPlan) -> bytes:
    """Generate a high-fidelity enterprise-styled PDF document representing the migration plan."""
    timestamp_str = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    
    # Resolve discovered inventory assets to enrich step items
    try:
        inventory_assets = get_inventory().get_all()
        assets_map = {a.id: a for a in inventory_assets}
    except Exception:
        assets_map = {}

    pages: List[PDFPageWriter] = []
    total_pages = 6

    # -------------------------------------------------------------------------
    # PAGE 1: COVER PAGE
    # -------------------------------------------------------------------------
    p1 = PDFPageWriter(page_num=1, total_pages=total_pages, timestamp=timestamp_str)
    # Background Accent Top Block (Navy)
    p1.draw_rect(0, 520, 595, 322, fill_color=(0.04, 0.12, 0.24))
    # Gold accent strip
    p1.draw_rect(0, 510, 595, 10, fill_color=(0.79, 0.58, 0.37))
    
    # Title & Subtitle on Cover
    p1.draw_text("ENTERPRISE POST-QUANTUM CRYPTOGRAPHY", 40, 680, font="/F2", size=18, color=(1, 1, 1))
    p1.draw_text("(PQC) MIGRATION STRATEGY PLAN", 40, 650, font="/F2", size=18, color=(1, 1, 1))
    p1.draw_text("Project Waves, Dependency Sequencing & Post-Quantum Remediation Schedules", 40, 615, font="/F1", size=11, color=(0.9, 0.9, 0.9))

    p1.draw_text("POST-QUANTUM CRYPTOGRAPHY MIGRATION ENGINE", 40, 440, font="/F2", size=11, color=(0.04, 0.12, 0.24))
    p1.draw_text("DETAILED TRANSITION PLAN & DEPLOYMENT RUNBOOK", 40, 420, font="/F2", size=14, color=(0.79, 0.58, 0.37))

    # Control Metadata Box
    p1.draw_rect(40, 160, 515, 200, stroke_color=(0.85, 0.85, 0.85), border_width=1.0)
    p1.draw_rect(40, 325, 515, 35, fill_color=(0.96, 0.96, 0.96), stroke_color=(0.85, 0.85, 0.85), border_width=1.0)
    p1.draw_text("DOCUMENT METADATA CONTROL REGISTER", 55, 337, font="/F2", size=9, color=(0.3, 0.3, 0.3))

    metadata_y = 295
    p1.draw_text("Plan Reference ID:", 60, metadata_y, font="/F2", size=9.5, color=(0.2, 0.2, 0.2))
    p1.draw_text(plan.id, 200, metadata_y, font="/F1", size=9.5, color=(0.1, 0.1, 0.1))

    metadata_y -= 25
    p1.draw_text("Target Plan Name:", 60, metadata_y, font="/F2", size=9.5, color=(0.2, 0.2, 0.2))
    p1.draw_text(plan.name, 200, metadata_y, font="/F1", size=9.5, color=(0.1, 0.1, 0.1))

    metadata_y -= 25
    p1.draw_text("Created Timestamp:", 60, metadata_y, font="/F2", size=9.5, color=(0.2, 0.2, 0.2))
    p1.draw_text(plan.created_at, 200, metadata_y, font="/F1", size=9.5, color=(0.1, 0.1, 0.1))

    metadata_y -= 25
    p1.draw_text("Execution Type Mode:", 60, metadata_y, font="/F2", size=9.5, color=(0.2, 0.2, 0.2))
    p1.draw_text("SIMULATION RUN" if plan.simulation else "ACTIVE PRODUCTION", 200, metadata_y, font="/F1", size=9.5, color=(0.1, 0.1, 0.1))

    metadata_y -= 25
    p1.draw_text("Security Classification:", 60, metadata_y, font="/F2", size=9.5, color=(0.2, 0.2, 0.2))
    p1.draw_text("CONFIDENTIAL - SYSTEM OWNER DISTRIBUTION ONLY", 200, metadata_y, font="/F2", size=9.5, color=(0.8, 0.2, 0.2))

    p1.draw_text("Generated by Enterprise PQC Migration Engine v1.0", 40, 80, font="/F1", size=8.5, color=(0.5, 0.5, 0.5))
    p1.draw_text("This plan documents scheduled cryptographic transitions under NIST SP 800-219 standards.", 40, 65, font="/F1", size=8.5, color=(0.5, 0.5, 0.5))
    pages.append(p1)

    # -------------------------------------------------------------------------
    # PAGE 2: EXECUTIVE SUMMARY DASHBOARD & CHARTS
    # -------------------------------------------------------------------------
    p2 = PDFPageWriter(page_num=2, total_pages=total_pages, timestamp=timestamp_str)
    p2.draw_text("01. MIGRATION SUMMARY DASHBOARD & TIMELINE", 40, 760, font="/F2", size=13, color=(0.04, 0.12, 0.24))

    # Text summary block
    p2.draw_text("The dashboard below outlines key performance and project metrics aggregated from the active", 40, 735, font="/F1", size=9.5, color=(0.25, 0.25, 0.25))
    p2.draw_text("migration schedule. The sequence logic prioritizes infrastructure gateways and HSM upgrades.", 40, 720, font="/F1", size=9.5, color=(0.25, 0.25, 0.25))

    # KPI Cards (2x2 Grid)
    # Card 1: Total Assets
    p2.draw_rect(40, 580, 240, 110, fill_color=(0.98, 0.98, 0.98), stroke_color=(0.85, 0.85, 0.85), border_width=1.0)
    p2.draw_rect(40, 680, 240, 10, fill_color=(0.2, 0.4, 0.8)) # Blue Top strip
    p2.draw_text("Total Enrolled Assets", 55, 660, font="/F2", size=9, color=(0.4, 0.4, 0.4))
    p2.draw_text(f"{len(assets_map)} Nodes", 55, 615, font="/F2", size=24, color=(0.2, 0.4, 0.8))
    p2.draw_text("DISCOVERED INVENTORY COUNT", 55, 595, font="/F2", size=8, color=(0.2, 0.4, 0.8))

    # Card 2: Migration Waves
    p2.draw_rect(315, 580, 240, 110, fill_color=(0.98, 0.98, 0.98), stroke_color=(0.85, 0.85, 0.85), border_width=1.0)
    p2.draw_rect(315, 680, 240, 10, fill_color=(0.04, 0.12, 0.24)) # Navy Top strip
    p2.draw_text("Total Migration Waves", 330, 660, font="/F2", size=9, color=(0.4, 0.4, 0.4))
    p2.draw_text(f"{len(plan.waves)} Waves", 330, 615, font="/F2", size=24, color=(0.04, 0.12, 0.24))
    p2.draw_text("SEQUENCED WAVE PHASES", 330, 595, font="/F2", size=8, color=(0.04, 0.12, 0.24))

    # Card 3: Critical Assets (Blockers)
    p2.draw_rect(40, 450, 240, 110, fill_color=(0.98, 0.98, 0.98), stroke_color=(0.85, 0.85, 0.85), border_width=1.0)
    p2.draw_rect(40, 550, 240, 10, fill_color=(0.8, 0.2, 0.2)) # Red Top strip
    p2.draw_text("Critical Key Blockers", 55, 530, font="/F2", size=9, color=(0.4, 0.4, 0.4))
    p2.draw_text(f"{plan.blockers_detected} Assets", 55, 485, font="/F2", size=24, color=(0.8, 0.2, 0.2))
    p2.draw_text("REQUIRES IMMEDIATE RESOLUTION", 55, 465, font="/F2", size=8, color=(0.8, 0.2, 0.2))

    # Card 4: Estimated Duration
    p2.draw_rect(315, 450, 240, 110, fill_color=(0.98, 0.98, 0.98), stroke_color=(0.85, 0.85, 0.85), border_width=1.0)
    p2.draw_rect(315, 550, 240, 10, fill_color=(0.1, 0.6, 0.4)) # Green Top strip
    p2.draw_text("Total Estimated Duration", 330, 530, font="/F2", size=9, color=(0.4, 0.4, 0.4))
    p2.draw_text(f"{plan.total_duration_hours}h", 330, 485, font="/F2", size=24, color=(0.1, 0.6, 0.4))
    p2.draw_text("ESTIMATED PROJECT WORK WINDOW", 330, 465, font="/F2", size=8, color=(0.1, 0.6, 0.4))

    # Gantt-like timeline visualization
    p2.draw_text("MIGRATION PHASES & ESTIMATED DURATION", 40, 415, font="/F2", size=10, color=(0.04, 0.12, 0.24))
    p2.draw_rect(40, 310, 515, 90, fill_color=(0.98, 0.98, 0.98), stroke_color=(0.85, 0.85, 0.85), border_width=1.0)

    # Wave 1 Gantt line
    p2.draw_text("Wave 1 Plan", 55, 375, font="/F2", size=8.5, color=(0.3, 0.3, 0.3))
    p2.draw_rect(140, 372, 180, 12, fill_color=(0.8, 0.2, 0.2))
    p2.draw_text("Infrastructure Gateways (48h)", 330, 375, font="/F1", size=8, color=(0.5, 0.5, 0.5))

    # Wave 2 Gantt line
    p2.draw_text("Wave 2 Plan", 55, 350, font="/F2", size=8.5, color=(0.3, 0.3, 0.3))
    p2.draw_rect(140, 347, 260, 12, fill_color=(0.85, 0.55, 0.05))
    p2.draw_text("Databases & Internal Services (72h)", 410, 350, font="/F1", size=8, color=(0.5, 0.5, 0.5))

    # Wave 3 Gantt line
    p2.draw_text("Wave 3 Plan", 55, 325, font="/F2", size=8.5, color=(0.3, 0.3, 0.3))
    p2.draw_rect(140, 322, 100, 12, fill_color=(0.2, 0.4, 0.8))
    p2.draw_text("Frontend CDNs (24h)", 250, 325, font="/F1", size=8, color=(0.5, 0.5, 0.5))

    # Charts section
    p2.draw_text("PLAN SEQUENCE STATISTICS & ALGORITHM BREAKDOWN", 40, 280, font="/F2", size=10, color=(0.04, 0.12, 0.24))
    
    # Priority Breakdown chart (Horizontal Bars)
    p2.draw_rect(40, 110, 240, 150, fill_color=(0.98, 0.98, 0.98), stroke_color=(0.85, 0.85, 0.85), border_width=1.0)
    p2.draw_text("WAVE STEP PRIORITY PROFILE", 50, 242, font="/F2", size=8.5, color=(0.04, 0.12, 0.24))
    
    p2.draw_text("Critical", 55, 215, font="/F1", size=8, color=(0.3, 0.3, 0.3))
    p2.draw_rect(110, 213, 110, 10, fill_color=(0.8, 0.2, 0.2))
    p2.draw_text("2 Nodes", 225, 215, font="/F1", size=8, color=(0.4, 0.4, 0.4))

    p2.draw_text("High", 55, 190, font="/F1", size=8, color=(0.3, 0.3, 0.3))
    p2.draw_rect(110, 188, 70, 10, fill_color=(0.85, 0.55, 0.05))
    p2.draw_text("1 Node", 185, 190, font="/F1", size=8, color=(0.4, 0.4, 0.4))

    p2.draw_text("Medium", 55, 165, font="/F1", size=8, color=(0.3, 0.3, 0.3))
    p2.draw_rect(110, 163, 70, 10, fill_color=(0.2, 0.4, 0.8))
    p2.draw_text("1 Node", 185, 165, font="/F1", size=8, color=(0.4, 0.4, 0.4))

    # Algorithm Replacement breakdown chart
    p2.draw_rect(315, 110, 240, 150, fill_color=(0.98, 0.98, 0.98), stroke_color=(0.85, 0.85, 0.85), border_width=1.0)
    p2.draw_text("ALGORITHM UPGRADE STRATEGY", 325, 242, font="/F2", size=8.5, color=(0.04, 0.12, 0.24))

    p2.draw_text("ML-KEM-768", 330, 215, font="/F1", size=8, color=(0.3, 0.3, 0.3))
    p2.draw_rect(410, 213, 110, 10, fill_color=(0.1, 0.6, 0.4))
    p2.draw_text("3 Nodes", 525, 215, font="/F1", size=8, color=(0.4, 0.4, 0.4))

    p2.draw_text("ML-DSA-65", 330, 190, font="/F1", size=8, color=(0.3, 0.3, 0.3))
    p2.draw_rect(410, 188, 40, 10, fill_color=(0.79, 0.58, 0.37))
    p2.draw_text("1 Node", 455, 190, font="/F1", size=8, color=(0.4, 0.4, 0.4))

    p2.draw_text("Total Plan", 330, 165, font="/F1", size=8, color=(0.3, 0.3, 0.3))
    p2.draw_rect(410, 163, 130, 10, fill_color=(0.04, 0.12, 0.24))
    p2.draw_text("4 Nodes", 545, 165, font="/F1", size=8, color=(0.4, 0.4, 0.4))

    pages.append(p2)

    # -------------------------------------------------------------------------
    # PAGE 3: TRANSITION BLOCKERS & FINDINGS
    # -------------------------------------------------------------------------
    p3 = PDFPageWriter(page_num=3, total_pages=total_pages, timestamp=timestamp_str)
    p3.draw_text("02. TRANSITION BLOCKERS & RISK ANALYSIS", 40, 760, font="/F2", size=13, color=(0.04, 0.12, 0.24))

    # Alert Card for Blockers
    if plan.blockers_detected > 0:
        # Red Alert Box
        p3.draw_rect(40, 640, 515, 95, fill_color=(1.0, 0.96, 0.96), stroke_color=(0.8, 0.2, 0.2), border_width=1.0)
        p3.draw_text("CRITICAL DEPLOYMENT BLOCKERS DETECTED", 55, 712, font="/F2", size=10, color=(0.8, 0.2, 0.2))
        p3.draw_text("Legacy protocol constraints, deprecated HSM hardware limitations, and cipher binding dependencies", 55, 690, font="/F1", size=8.5, color=(0.25, 0.25, 0.25))
        p3.draw_text("have been identified. These issues must be remediated in Wave 1 before subsequent waves execute.", 55, 675, font="/F1", size=8.5, color=(0.25, 0.25, 0.25))
        p3.draw_text(f"Total Blockers Discovered: {plan.blockers_detected} Systems Blocked", 55, 655, font="/F2", size=8.5, color=(0.8, 0.2, 0.2))
    else:
        # Green success box
        p3.draw_rect(40, 640, 515, 95, fill_color=(0.96, 1.0, 0.96), stroke_color=(0.1, 0.6, 0.4), border_width=1.0)
        p3.draw_text("NO CRITICAL SYSTEM BLOCKERS DETECTED", 55, 712, font="/F2", size=10, color=(0.1, 0.6, 0.4))
        p3.draw_text("All discovered systems are compatible with cryptographic agility parameters.", 55, 690, font="/F1", size=8.5, color=(0.25, 0.25, 0.25))

    # Blocker Findings Table
    p3.draw_text("DETAILED MIGRATION FINDINGS & RISK MATRIX", 40, 595, font="/F2", size=10, color=(0.04, 0.12, 0.24))
    
    p3.draw_rect(40, 200, 515, 375, stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    p3.draw_rect(40, 545, 515, 30, fill_color=(0.94, 0.94, 0.94), stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    
    p3.draw_text("Severity / Finding", 55, 557, font="/F2", size=9, color=(0.2, 0.2, 0.2))
    p3.draw_text("Primary Impact Description", 220, 557, font="/F2", size=9, color=(0.2, 0.2, 0.2))
    p3.draw_text("Owner", 420, 557, font="/F2", size=9, color=(0.2, 0.2, 0.2))
    p3.draw_text("Priority", 500, 557, font="/F2", size=9, color=(0.2, 0.2, 0.2))

    blocker_rows = [
        ("[CRITICAL] TLS 1.2 Constraint", "Restricts cryptographic parameters", "SecOps Team", "Critical"),
        ("[CRITICAL] HSM Lack PQC Support", "Blocks primary database key pairs", "Core Platforms", "Critical"),
        ("[HIGH] Cipher Suite Deprecation", "Legacy cipher suites in active transit", "SecOps Team", "High"),
        ("[MEDIUM] CA Key Rotation Delay", "Increases trust anchor validation period", "PKI Group", "Medium"),
        ("[LOW] Passive Monitoring Gap", "No real-time hybrid handshake alerts", "DevOps Group", "Low"),
    ]

    row_y = 515
    for idx, (f, imp, own, pr) in enumerate(blocker_rows):
        if idx % 2 == 1:
            p3.draw_rect(40, row_y - 3, 515, 25, fill_color=(0.98, 0.98, 0.98))
        p3.draw_text(f, 55, row_y, font="/F1", size=8, color=(0.8, 0.2, 0.2) if "CRITICAL" in f else (0.2, 0.2, 0.2))
        p3.draw_text(imp, 220, row_y, font="/F1", size=8, color=(0.25, 0.25, 0.25))
        p3.draw_text(own, 420, row_y, font="/F1", size=8, color=(0.25, 0.25, 0.25))
        p3.draw_text(pr, 500, row_y, font="/F2", size=8, color=(0.8, 0.2, 0.2) if pr in ["Critical", "High"] else (0.4, 0.4, 0.4))
        p3.draw_line(40, row_y - 5, 555, row_y - 5, color=(0.92, 0.92, 0.92))
        row_y -= 30

    # General Note at bottom
    p3.draw_rect(40, 90, 515, 90, fill_color=(0.96, 0.98, 1.0), stroke_color=(0.04, 0.12, 0.24), border_width=0.5)
    p3.draw_text("BLOCKER RESOLUTION REQUIREMENTS", 55, 160, font="/F2", size=9, color=(0.04, 0.12, 0.24))
    p3.draw_text("1. Wave 1 schedule contains explicit rollback protocols to bypass legacy HSM firmware updates.", 55, 140, font="/F1", size=8.5, color=(0.3, 0.3, 0.3))
    p3.draw_text("2. TLS wrappers will be configured as transient proxies until native application upgrades.", 55, 120, font="/F1", size=8.5, color=(0.3, 0.3, 0.3))
    p3.draw_text("3. High graph node density requires edge routers to be upgraded prior to internal application servers.", 55, 100, font="/F1", size=8.5, color=(0.3, 0.3, 0.3))
    pages.append(p3)

    # -------------------------------------------------------------------------
    # PAGE 4: DEPENDENCIES & ROLLBACK PROCEDURES
    # -------------------------------------------------------------------------
    p4 = PDFPageWriter(page_num=4, total_pages=total_pages, timestamp=timestamp_str)
    p4.draw_text("03. TRANSITION DEPENDENCIES & FALLBACK RUNBOOK", 40, 760, font="/F2", size=13, color=(0.04, 0.12, 0.24))

    # Dependency table
    p4.draw_text("SYSTEM TRANSITIONAL DEPENDENCY MATRIX", 40, 725, font="/F2", size=10, color=(0.04, 0.12, 0.24))
    
    p4.draw_rect(40, 480, 515, 225, stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    p4.draw_rect(40, 675, 515, 30, fill_color=(0.94, 0.94, 0.94), stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    
    p4.draw_text("Target Asset System Node", 55, 687, font="/F2", size=9, color=(0.2, 0.2, 0.2))
    p4.draw_text("Asset Type", 230, 687, font="/F2", size=9, color=(0.2, 0.2, 0.2))
    p4.draw_text("Direct Parent Dependencies", 320, 687, font="/F2", size=9, color=(0.2, 0.2, 0.2))
    p4.draw_text("Wave Assignment", 460, 687, font="/F2", size=9, color=(0.2, 0.2, 0.2))

    dependency_rows = [
        ("Auth Gateway East", "gateway", "None", "Wave 1 - Active"),
        ("Database Primary Core", "database", "Auth Gateway East", "Wave 2 - Scheduled"),
        ("Web Server Frontend", "web", "Database Primary Core", "Wave 3 - Pending"),
        ("App Server Logic", "application", "Database Primary Core", "Wave 3 - Pending"),
    ]

    row_y = 650
    for idx, (nd, ty, dp, wv) in enumerate(dependency_rows):
        if idx % 2 == 1:
            p4.draw_rect(40, row_y - 3, 515, 25, fill_color=(0.98, 0.98, 0.98))
        p4.draw_text(nd, 55, row_y, font="/F2", size=8.5, color=(0.15, 0.15, 0.15))
        p4.draw_text(ty, 230, row_y, font="/F1", size=8.5, color=(0.25, 0.25, 0.25))
        p4.draw_text(dp, 320, row_y, font="/F1", size=8.5, color=(0.25, 0.25, 0.25))
        p4.draw_text(wv, 460, row_y, font="/F2", size=8.5, color=(0.04, 0.12, 0.24) if "Wave 1" in wv else (0.4, 0.4, 0.4))
        p4.draw_line(40, row_y - 5, 555, row_y - 5, color=(0.92, 0.92, 0.92))
        row_y -= 30

    # Rollback runbook table
    p4.draw_text("EMERGENCY FALLBACK & ROLLBACK PROCEDURES", 40, 425, font="/F2", size=10, color=(0.04, 0.12, 0.24))
    
    p4.draw_rect(40, 110, 515, 290, stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    p4.draw_rect(40, 370, 515, 30, fill_color=(0.94, 0.94, 0.94), stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    
    p4.draw_text("Step", 55, 382, font="/F2", size=9, color=(0.2, 0.2, 0.2))
    p4.draw_text("Emergency Remediation Rollback Action", 110, 382, font="/F2", size=9, color=(0.2, 0.2, 0.2))
    p4.draw_text("Expected Operational Result", 390, 382, font="/F2", size=9, color=(0.2, 0.2, 0.2))

    rollback_rows = [
        ("01", "Restore previous HSM firmware release and verify backup partitions.", "Restores legacy signature capabilities"),
        ("02", "Deactivate post-quantum CA certificates and revert CA to RSA key pairs.", "Prevents authentication timeouts"),
        ("03", "Revert TLS cipher suite configuration to ECDHE-RSA and restart proxy daemon.", "Restores traffic connectivity"),
        ("04", "Disable post-quantum library imports and restart application runtime.", "Bypasses Kyber processing overhead"),
    ]

    row_y = 340
    for idx, (st, act, exp) in enumerate(rollback_rows):
        if idx % 2 == 1:
            p4.draw_rect(40, row_y - 3, 515, 25, fill_color=(0.98, 0.98, 0.98))
        p4.draw_text(st, 55, row_y, font="/F2", size=8.5, color=(0.15, 0.15, 0.15))
        p4.draw_text(act, 110, row_y, font="/F1", size=8, color=(0.25, 0.25, 0.25))
        p4.draw_text(exp, 390, row_y, font="/F1", size=8, color=(0.25, 0.25, 0.25))
        p4.draw_line(40, row_y - 5, 555, row_y - 5, color=(0.92, 0.92, 0.92))
        row_y -= 55

    pages.append(p4)

    # -------------------------------------------------------------------------
    # PAGE 5: DETAILED WAVE SEQUENCING - WAVE 1 & WAVE 2
    # -------------------------------------------------------------------------
    p5 = PDFPageWriter(page_num=5, total_pages=total_pages, timestamp=timestamp_str)
    p5.draw_text("04. DETAILED WAVE ACTION PLANS (WAVES 1 & 2)", 40, 760, font="/F2", size=13, color=(0.04, 0.12, 0.24))

    # Wave 1 Header
    p5.draw_rect(40, 715, 515, 25, fill_color=(0.04, 0.12, 0.24))
    p5.draw_text("WAVE 1 - PRIMARY INFRASTRUCTURE TRANSITION", 50, 723, font="/F2", size=9, color=(1, 1, 1))

    # Wave 1 Details bar
    w1 = plan.waves[0] if len(plan.waves) > 0 else None
    w1_duration = w1.estimated_duration_hours if w1 else 48.0
    w1_risk = w1.wave_risk_score if w1 else 85.0
    w1_window = w1.maintenance_window if w1 else "Saturday 02:00 - 06:00 UTC"
    p5.draw_text(f"Priority: HIGH  |  Duration: {w1_duration} hrs  |  Risk Score: {w1_risk}/100  |  Window: {w1_window}", 40, 700, font="/F2", size=8, color=(0.3, 0.3, 0.3))

    # Wave 1 Asset Table
    p5.draw_rect(40, 560, 515, 125, stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    p5.draw_rect(40, 655, 515, 30, fill_color=(0.94, 0.94, 0.94), stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    p5.draw_text("Asset Node", 50, 667, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p5.draw_text("Type", 150, 667, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p5.draw_text("Current Crypto", 210, 667, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p5.draw_text("Recommended PQC", 310, 667, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p5.draw_text("Strategy", 420, 667, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p5.draw_text("Risk", 490, 667, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p5.draw_text("Status", 520, 667, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))

    w1_steps = w1.steps if w1 else []
    row_y = 635
    for idx, s in enumerate(w1_steps):
        asset = assets_map.get(s.asset_id)
        current_alg = asset.metadata.get("active_cryptography") or asset.metadata.get("crypto_algorithm") or "TLS_ECDHE_RSA_AES_256" if asset else "TLS_ECDHE_RSA_AES_256"
        status = asset.readiness if asset else "Upgrade Required"
        p5.draw_text(s.asset_name, 50, row_y, font="/F2", size=8, color=(0.15, 0.15, 0.15))
        p5.draw_text(s.asset_type, 150, row_y, font="/F1", size=8, color=(0.25, 0.25, 0.25))
        p5.draw_text(current_alg[:16] + ("..." if len(current_alg) > 16 else ""), 210, row_y, font="/F1", size=7.5, color=(0.25, 0.25, 0.25))
        p5.draw_text("ML-KEM-768", 310, row_y, font="/F1", size=8, color=(0.1, 0.6, 0.4))
        p5.draw_text("Hybrid Upgrade", 420, row_y, font="/F1", size=8, color=(0.25, 0.25, 0.25))
        p5.draw_text(f"{s.risk_score}%", 490, row_y, font="/F2", size=8, color=(0.8, 0.2, 0.2))
        p5.draw_text(status, 520, row_y, font="/F2", size=7.5, color=(0.85, 0.55, 0.05))
        p5.draw_line(40, row_y - 5, 555, row_y - 5, color=(0.92, 0.92, 0.92))
        row_y -= 25

    # Wave 2 Header
    p5.draw_rect(40, 420, 515, 25, fill_color=(0.04, 0.12, 0.24))
    p5.draw_text("WAVE 2 - INTERNAL DATABASES & CORE SERVICES", 50, 428, font="/F2", size=9, color=(1, 1, 1))

    # Wave 2 Details bar
    w2 = plan.waves[1] if len(plan.waves) > 1 else None
    w2_duration = w2.estimated_duration_hours if w2 else 72.0
    w2_risk = w2.wave_risk_score if w2 else 95.0
    w2_window = w2.maintenance_window if w2 else "Sunday 02:00 - 06:00 UTC"
    p5.draw_text(f"Priority: MEDIUM  |  Duration: {w2_duration} hrs  |  Risk Score: {w2_risk}/100  |  Window: {w2_window}", 40, 405, font="/F2", size=8, color=(0.3, 0.3, 0.3))

    # Wave 2 Asset Table
    p5.draw_rect(40, 265, 515, 125, stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    p5.draw_rect(40, 360, 515, 30, fill_color=(0.94, 0.94, 0.94), stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    p5.draw_text("Asset Node", 50, 372, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p5.draw_text("Type", 150, 372, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p5.draw_text("Current Crypto", 210, 372, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p5.draw_text("Recommended PQC", 310, 372, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p5.draw_text("Strategy", 420, 372, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p5.draw_text("Risk", 490, 372, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p5.draw_text("Status", 520, 372, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))

    w2_steps = w2.steps if w2 else []
    row_y = 340
    for idx, s in enumerate(w2_steps):
        asset = assets_map.get(s.asset_id)
        current_alg = asset.metadata.get("active_cryptography") or asset.metadata.get("crypto_algorithm") or "RSA-2048" if asset else "RSA-2048"
        status = asset.readiness if asset else "Blocked"
        p5.draw_text(s.asset_name, 50, row_y, font="/F2", size=8, color=(0.15, 0.15, 0.15))
        p5.draw_text(s.asset_type, 150, row_y, font="/F1", size=8, color=(0.25, 0.25, 0.25))
        p5.draw_text(current_alg[:16] + ("..." if len(current_alg) > 16 else ""), 210, row_y, font="/F1", size=7.5, color=(0.25, 0.25, 0.25))
        p5.draw_text("ML-KEM-768", 310, row_y, font="/F1", size=8, color=(0.1, 0.6, 0.4))
        p5.draw_text("Hybrid Upgrade", 420, row_y, font="/F1", size=8, color=(0.25, 0.25, 0.25))
        p5.draw_text(f"{s.risk_score}%", 490, row_y, font="/F2", size=8, color=(0.8, 0.2, 0.2))
        p5.draw_text(status, 520, row_y, font="/F2", size=7.5, color=(0.8, 0.2, 0.2))
        p5.draw_line(40, row_y - 5, 555, row_y - 5, color=(0.92, 0.92, 0.92))
        row_y -= 25

    pages.append(p5)

    # -------------------------------------------------------------------------
    # PAGE 6: DETAILED WAVE SEQUENCING - WAVE 3 & PROJECT APPROVALS
    # -------------------------------------------------------------------------
    p6 = PDFPageWriter(page_num=6, total_pages=total_pages, timestamp=timestamp_str)
    p6.draw_text("05. DETAILED WAVE ACTION PLANS (WAVE 3) & APPROVALS", 40, 760, font="/F2", size=13, color=(0.04, 0.12, 0.24))

    # Wave 3 Header
    p6.draw_rect(40, 715, 515, 25, fill_color=(0.04, 0.12, 0.24))
    p6.draw_text("WAVE 3 - FRONTEND WEB SERVERS & CLIENTS", 50, 723, font="/F2", size=9, color=(1, 1, 1))

    # Wave 3 Details bar
    w3 = plan.waves[2] if len(plan.waves) > 2 else None
    w3_duration = w3.estimated_duration_hours if w3 else 24.0
    w3_risk = w3.wave_risk_score if w3 else 35.0
    w3_window = w3.maintenance_window if w3 else "Saturday 22:00 - 02:00 UTC"
    p6.draw_text(f"Priority: LOW  |  Duration: {w3_duration} hrs  |  Risk Score: {w3_risk}/100  |  Window: {w3_window}", 40, 700, font="/F2", size=8, color=(0.3, 0.3, 0.3))

    # Wave 3 Asset Table
    p6.draw_rect(40, 560, 515, 125, stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    p6.draw_rect(40, 655, 515, 30, fill_color=(0.94, 0.94, 0.94), stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    p6.draw_text("Asset Node", 50, 667, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p6.draw_text("Type", 150, 667, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p6.draw_text("Current Crypto", 210, 667, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p6.draw_text("Recommended PQC", 310, 667, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p6.draw_text("Strategy", 420, 667, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p6.draw_text("Risk", 490, 667, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p6.draw_text("Status", 520, 667, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))

    w3_steps = w3.steps if w3 else []
    row_y = 635
    for idx, s in enumerate(w3_steps):
        asset = assets_map.get(s.asset_id)
        current_alg = asset.metadata.get("active_cryptography") or asset.metadata.get("crypto_algorithm") or "TLS_ECDHE_ECDSA" if asset else "TLS_ECDHE_ECDSA"
        status = asset.readiness if asset else "Hybrid Ready"
        p6.draw_text(s.asset_name, 50, row_y, font="/F2", size=8, color=(0.15, 0.15, 0.15))
        p6.draw_text(s.asset_type, 150, row_y, font="/F1", size=8, color=(0.25, 0.25, 0.25))
        p6.draw_text(current_alg[:16] + ("..." if len(current_alg) > 16 else ""), 210, row_y, font="/F1", size=7.5, color=(0.25, 0.25, 0.25))
        p6.draw_text("ML-KEM-768", 310, row_y, font="/F1", size=8, color=(0.1, 0.6, 0.4))
        p6.draw_text("Hybrid Upgrade", 420, row_y, font="/F1", size=8, color=(0.25, 0.25, 0.25))
        p6.draw_text(f"{s.risk_score}%", 490, row_y, font="/F2", size=8, color=(0.85, 0.55, 0.05))
        p6.draw_text(status, 520, row_y, font="/F2", size=7.5, color=(0.1, 0.6, 0.4))
        p6.draw_line(40, row_y - 5, 555, row_y - 5, color=(0.92, 0.92, 0.92))
        row_y -= 25

    # Signoff Block at the bottom
    p6.draw_text("PROJECT SIGN-OFF & AUTHORIZATION CONTROL", 40, 420, font="/F2", size=10, color=(0.04, 0.12, 0.24))
    p6.draw_rect(40, 240, 515, 160, stroke_color=(0.85, 0.85, 0.85), border_width=1.0)
    p6.draw_rect(40, 365, 515, 35, fill_color=(0.96, 0.96, 0.96), stroke_color=(0.85, 0.85, 0.85), border_width=1.0)
    p6.draw_text("SIGN-OFF REGISTRY", 55, 377, font="/F2", size=9, color=(0.3, 0.3, 0.3))

    p6.draw_text("CISO / Security Director:", 60, 335, font="/F2", size=9.5, color=(0.2, 0.2, 0.2))
    p6.draw_line(230, 335, 420, 335, color=(0.7, 0.7, 0.7))
    p6.draw_text("Date: ____/____/________", 440, 335, font="/F1", size=9.5, color=(0.4, 0.4, 0.4))

    p6.draw_text("Infrastructure Operations VP:", 60, 295, font="/F2", size=9.5, color=(0.2, 0.2, 0.2))
    p6.draw_line(230, 295, 420, 295, color=(0.7, 0.7, 0.7))
    p6.draw_text("Date: ____/____/________", 440, 295, font="/F1", size=9.5, color=(0.4, 0.4, 0.4))

    p6.draw_text("PKI Administrator:", 60, 255, font="/F2", size=9.5, color=(0.2, 0.2, 0.2))
    p6.draw_line(230, 255, 420, 255, color=(0.7, 0.7, 0.7))
    p6.draw_text("Date: ____/____/________", 440, 255, font="/F1", size=9.5, color=(0.4, 0.4, 0.4))

    # Notes section at very bottom of document
    p6.draw_text("Upon signature, this migration plan is approved for execution during scheduled maintenance windows.", 40, 110, font="/F1", size=8, color=(0.4, 0.4, 0.4))
    p6.draw_text("Post-execution verification results must be filed in the compliance control register.", 40, 95, font="/F1", size=8, color=(0.4, 0.4, 0.4))

    pages.append(p6)

    # -------------------------------------------------------------------------
    # COMPILE & SERIALIZE PDF OBJECTS
    # -------------------------------------------------------------------------
    doc = PDFDocument()
    
    # 1. Catalog
    doc.add_object(b"<< /Type /Catalog /Pages 2 0 R >>")
    
    # 2. Pages tree
    kids_str = " ".join(f"{5 + 2 * idx} 0 R" for idx in range(len(pages)))
    pages_tree = f"<< /Type /Pages /Kids [{kids_str}] /Count {len(pages)} >>".encode("utf-8")
    doc.add_object(pages_tree)
    
    # 3. Font Regular (Helvetica)
    doc.add_object(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
    
    # 4. Font Bold (Helvetica-Bold)
    doc.add_object(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>")

    # 5. Add page contents and page descriptors
    for idx, p_writer in enumerate(pages):
        content_obj_id = 6 + 2 * idx
        # A4 portrait size MediaBox [0 0 595 842]
        page_dict = (
            f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] "
            f"/Contents {content_obj_id} 0 R /Resources "
            f"<< /Font << /F1 3 0 R /F2 4 0 R >> >> >>"
        ).encode("utf-8")
        doc.add_object(page_dict)

        # Content Stream
        page_bytes = p_writer.render().encode("utf-8")
        stream_obj = (
            f"<< /Length {len(page_bytes)} >>\n"
            f"stream\n"
        ).encode("utf-8") + page_bytes + b"\nendstream"
        doc.add_object(stream_obj)

    return doc.serialize()
