"""
Reports exporter — native PDF generation from raw byte streams
complying with the PDF-1.4 specification without external dependencies.
Optimized for A4 portrait layout with high-end typography and styling.
"""

from typing import List, Dict, Any
from app.reports.models import DeploymentReport


class PDFDocument:
    """Helper to assemble a PDF structure and calculate offsets for the cross-reference table."""

    def __init__(self) -> None:
        self.objects: List[bytes] = []

    def add_object(self, obj_bytes: bytes) -> int:
        """Add an object's payload to the list and return its 1-indexed object ID."""
        self.objects.append(obj_bytes)
        return len(self.objects)

    def serialize(self) -> bytes:
        """Compile the objects, cross-reference table, and trailer into PDF bytes."""
        out = bytearray()
        out.extend(b"%PDF-1.4\n")

        offsets = {}
        # Serialize objects
        for idx, obj in enumerate(self.objects):
            obj_id = idx + 1
            offsets[obj_id] = len(out)
            out.extend(f"{obj_id} 0 obj\n".encode("utf-8"))
            out.extend(obj)
            out.extend(b"\nendobj\n")

        # Start of cross-reference table
        xref_start = len(out)
        out.extend(b"xref\n")
        # 0 object + active objects
        out.extend(f"0 {len(self.objects) + 1}\n".encode("utf-8"))
        # First entry: free object list head
        out.extend(b"0000000000 65535 f \n")
        
        # Write offsets for each object
        for obj_id in range(1, len(self.objects) + 1):
            offset = offsets[obj_id]
            out.extend(f"{offset:010d} 00000 n \n".encode("utf-8"))

        out.extend(b"trailer\n")
        out.extend(f"<< /Size {len(self.objects) + 1} /Root 1 0 R >>\n".encode("utf-8"))
        out.extend(b"startxref\n")
        out.extend(f"{xref_start}\n".encode("utf-8"))
        out.extend(b"%%EOF\n")

        return bytes(out)


def escape_pdf_str(text: str) -> str:
    """Escape parentheses and backslashes for PDF string fields."""
    return (
        str(text)
        .replace("\\", "\\\\")
        .replace("(", "\\(")
        .replace(")", "\\)")
    )


class PDFPageWriter:
    """Helper to write PDF content stream commands for a single A4 page (595 x 842 pt)."""

    def __init__(self, page_num: int, total_pages: int = 9) -> None:
        self.page_num = page_num
        self.total_pages = total_pages
        self.width = 595
        self.height = 842
        self.commands: List[str] = []

        # Standard header/footer for all pages except cover page (page 1)
        if self.page_num > 1:
            self.draw_header_footer()

    def add_cmd(self, cmd: str) -> None:
        self.commands.append(cmd)

    def draw_line(self, x1: float, y1: float, x2: float, y2: float, color=(0.8, 0.8, 0.8), width=0.5) -> None:
        self.add_cmd(f"{width} w")
        self.add_cmd(f"{color[0]} {color[1]} {color[2]} RG")
        self.add_cmd(f"{x1} {y1} m {x2} {y2} l s")

    def draw_rect(self, x: float, y: float, w: float, h: float, fill_color=None, stroke_color=None, border_width=0.5) -> None:
        if fill_color:
            self.add_cmd(f"{fill_color[0]} {fill_color[1]} {fill_color[2]} rg")
        if stroke_color:
            self.add_cmd(f"{border_width} w")
            self.add_cmd(f"{stroke_color[0]} {stroke_color[1]} {stroke_color[2]} RG")
        
        self.add_cmd(f"{x} {y} {w} {h} re")
        if fill_color and stroke_color:
            self.add_cmd("B")
        elif fill_color:
            self.add_cmd("f")
        elif stroke_color:
            self.add_cmd("s")

    def draw_text(self, text: str, x: float, y: float, font="/F1", size=10, color=(0.1, 0.1, 0.1)) -> None:
        self.add_cmd("BT")
        self.add_cmd(f"{color[0]} {color[1]} {color[2]} rg")
        self.add_cmd(f"{font} {size} Tf")
        self.add_cmd(f"{x} {y} Td")
        self.add_cmd(f"({escape_pdf_str(text)}) Tj")
        self.add_cmd("ET")

    def draw_header_footer(self) -> None:
        # Running Header
        self.draw_text("Enterprise PQC Migration Assessment Report", 40, 805, font="/F2", size=8, color=(0.4, 0.4, 0.4))
        self.draw_text("CONFIDENTIAL", 500, 805, font="/F2", size=8, color=(0.8, 0.2, 0.2))
        self.draw_line(40, 797, 555, 797, color=(0.85, 0.85, 0.85), width=0.5)

        # Running Footer
        self.draw_line(40, 48, 555, 48, color=(0.85, 0.85, 0.85), width=0.5)
        self.draw_text("Generated by Enterprise PQC Migration Engine", 40, 32, font="/F1", size=8, color=(0.5, 0.5, 0.5))
        self.draw_text(f"Page {self.page_num} of {self.total_pages}", 505, 32, font="/F1", size=8, color=(0.5, 0.5, 0.5))

    def render(self) -> str:
        return "\n".join(self.commands)


def export_report_to_pdf(report: DeploymentReport) -> bytes:
    """Generate a formatted multi-page PDF document representing the consolidated deployment report."""
    pages: List[PDFPageWriter] = []
    total_pages = 9

    # -------------------------------------------------------------------------
    # PAGE 1: COVER PAGE
    # -------------------------------------------------------------------------
    p1 = PDFPageWriter(page_num=1, total_pages=total_pages)
    # Background Accent Top Block
    p1.draw_rect(0, 520, 595, 322, fill_color=(0.04, 0.12, 0.24)) # Dark Navy
    # Gold accent strip
    p1.draw_rect(0, 510, 595, 10, fill_color=(0.79, 0.58, 0.37)) # Gold
    
    # Title
    p1.draw_text("ENTERPRISE POST-QUANTUM CRYPTOGRAPHY", 40, 680, font="/F2", size=18, color=(1, 1, 1))
    p1.draw_text("(PQC) MIGRATION ASSESSMENT REPORT", 40, 650, font="/F2", size=18, color=(1, 1, 1))
    p1.draw_text("Quantum Vulnerability Discovery, Performance Benchmarks & Sequencing", 40, 615, font="/F1", size=11, color=(0.9, 0.9, 0.9))

    # Subtitle
    p1.draw_text("POST-QUANTUM CRYPTOGRAPHY MIGRATION ENGINE", 40, 440, font="/F2", size=11, color=(0.04, 0.12, 0.24))
    p1.draw_text("CONSOLIDATED COMPLIANCE & SCHEDULING PLAN", 40, 420, font="/F2", size=15, color=(0.79, 0.58, 0.37))

    # Metadata Card Border
    p1.draw_rect(40, 160, 515, 200, stroke_color=(0.85, 0.85, 0.85), border_width=1.0)
    p1.draw_rect(40, 325, 515, 35, fill_color=(0.96, 0.96, 0.96), stroke_color=(0.85, 0.85, 0.85), border_width=1.0)
    p1.draw_text("DOCUMENT METADATA CONTROL REGISTER", 55, 337, font="/F2", size=9, color=(0.3, 0.3, 0.3))

    metadata_y = 295
    p1.draw_text("Report Reference ID:", 60, metadata_y, font="/F2", size=9.5, color=(0.2, 0.2, 0.2))
    p1.draw_text(report.id, 200, metadata_y, font="/F1", size=9.5, color=(0.1, 0.1, 0.1))

    metadata_y -= 25
    p1.draw_text("Report Target Name:", 60, metadata_y, font="/F2", size=9.5, color=(0.2, 0.2, 0.2))
    p1.draw_text(report.name, 200, metadata_y, font="/F1", size=9.5, color=(0.1, 0.1, 0.1))

    metadata_y -= 25
    p1.draw_text("Generated Timestamp:", 60, metadata_y, font="/F2", size=9.5, color=(0.2, 0.2, 0.2))
    p1.draw_text(report.created_at, 200, metadata_y, font="/F1", size=9.5, color=(0.1, 0.1, 0.1))

    metadata_y -= 25
    p1.draw_text("Total Enrolled Assets:", 60, metadata_y, font="/F2", size=9.5, color=(0.2, 0.2, 0.2))
    p1.draw_text(f"{report.statistics.total_assets} Active Nodes", 200, metadata_y, font="/F1", size=9.5, color=(0.1, 0.1, 0.1))

    metadata_y -= 25
    p1.draw_text("Security Classification:", 60, metadata_y, font="/F2", size=9.5, color=(0.2, 0.2, 0.2))
    p1.draw_text("CONFIDENTIAL - SYSTEM OWNER DISTRIBUTION ONLY", 200, metadata_y, font="/F2", size=9.5, color=(0.8, 0.2, 0.2))

    # Bottom Footer on Cover
    p1.draw_text("Generated by Enterprise PQC Migration Engine v1.0", 40, 80, font="/F1", size=8.5, color=(0.5, 0.5, 0.5))
    p1.draw_text("This document contains proprietary audit details for cryptography compliance under FIPS standards.", 40, 65, font="/F1", size=8.5, color=(0.5, 0.5, 0.5))
    pages.append(p1)

    # -------------------------------------------------------------------------
    # PAGE 2: EXECUTIVE SUMMARY & DASHBOARD
    # -------------------------------------------------------------------------
    p2 = PDFPageWriter(page_num=2, total_pages=total_pages)
    p2.draw_text("01. EXECUTIVE SUMMARY & DASHBOARD", 40, 760, font="/F2", size=13, color=(0.04, 0.12, 0.24))
    
    # Text summary block
    p2.draw_text("The following matrix summarizes discovered cryptographic vulnerabilities and transitional", 40, 735, font="/F1", size=9.5, color=(0.25, 0.25, 0.25))
    p2.draw_text("PQC profiles. Strategic scheduling actions have been developed according to NIST guidelines.", 40, 720, font="/F1", size=9.5, color=(0.25, 0.25, 0.25))

    # KPI Cards (2x2 Grid)
    # Card 1: Overall Risk
    p2.draw_rect(40, 580, 240, 110, fill_color=(0.98, 0.98, 0.98), stroke_color=(0.85, 0.85, 0.85), border_width=1.0)
    p2.draw_rect(40, 680, 240, 10, fill_color=(0.8, 0.2, 0.2)) # Red Top strip
    p2.draw_text("Overall Migration Risk", 55, 660, font="/F2", size=9, color=(0.4, 0.4, 0.4))
    p2.draw_text(f"{report.statistics.overall_migration_risk}%", 55, 615, font="/F2", size=24, color=(0.8, 0.2, 0.2))
    p2.draw_text("HIGH RISK THREAT LEVEL", 55, 595, font="/F2", size=8, color=(0.8, 0.2, 0.2))

    # Card 2: Migration Readiness
    p2.draw_rect(315, 580, 240, 110, fill_color=(0.98, 0.98, 0.98), stroke_color=(0.85, 0.85, 0.85), border_width=1.0)
    p2.draw_rect(315, 680, 240, 10, fill_color=(0.1, 0.6, 0.4)) # Green Top strip
    p2.draw_text("Average Readiness Score", 330, 660, font="/F2", size=9, color=(0.4, 0.4, 0.4))
    p2.draw_text(f"{report.statistics.overall_readiness_score}%", 330, 615, font="/F2", size=24, color=(0.1, 0.6, 0.4))
    p2.draw_text("UPGRADE REQUIRED", 330, 595, font="/F2", size=8, color=(0.8, 0.5, 0.1))

    # Card 3: Critical Assets
    p2.draw_rect(40, 450, 240, 110, fill_color=(0.98, 0.98, 0.98), stroke_color=(0.85, 0.85, 0.85), border_width=1.0)
    p2.draw_rect(40, 550, 240, 10, fill_color=(0.79, 0.58, 0.37)) # Gold Top strip
    p2.draw_text("Total Critical Assets", 55, 530, font="/F2", size=9, color=(0.4, 0.4, 0.4))
    p2.draw_text(f"{report.statistics.total_assets} Nodes", 55, 485, font="/F2", size=22, color=(0.15, 0.15, 0.15))
    p2.draw_text(f"{report.statistics.legacy_blockers} Legacy Blockers Discovered", 55, 465, font="/F1", size=8, color=(0.5, 0.5, 0.5))

    # Card 4: Migration Duration
    p2.draw_rect(315, 450, 240, 110, fill_color=(0.98, 0.98, 0.98), stroke_color=(0.85, 0.85, 0.85), border_width=1.0)
    p2.draw_rect(315, 550, 240, 10, fill_color=(0.04, 0.12, 0.24)) # Navy Top strip
    p2.draw_text("Projected Duration", 330, 530, font="/F2", size=9, color=(0.4, 0.4, 0.4))
    p2.draw_text(f"{report.statistics.estimated_migration_duration}h", 330, 485, font="/F2", size=24, color=(0.04, 0.12, 0.24))
    p2.draw_text("Estimated Transition Window", 330, 465, font="/F1", size=8, color=(0.5, 0.5, 0.5))

    # Executive Summary Table
    p2.draw_text("EXECUTIVE COMPLIANCE SUMMARY MATRIX", 40, 415, font="/F2", size=10, color=(0.04, 0.12, 0.24))
    
    # Draw table outline
    p2.draw_rect(40, 210, 515, 190, stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    # Header Row
    p2.draw_rect(40, 375, 515, 25, fill_color=(0.94, 0.94, 0.94), stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    p2.draw_text("Metric Evaluated", 55, 383, font="/F2", size=9, color=(0.2, 0.2, 0.2))
    p2.draw_text("Assessed Value", 280, 383, font="/F2", size=9, color=(0.2, 0.2, 0.2))
    p2.draw_text("Remediation Status", 440, 383, font="/F2", size=9, color=(0.2, 0.2, 0.2))

    summary_rows = [
      ("Total Discovered Infrastructure Nodes", f"{report.statistics.total_assets} Assets", "In Review"),
      ("Overall Quantum Threat Vulnerability", f"{report.statistics.overall_migration_risk}%", "Action Required"),
      ("Average Hybrid-PQC Readiness Ratio", f"{report.statistics.overall_readiness_score}%", "In Progress"),
      ("Total Active Legacy Key Blockers", f"{report.statistics.legacy_blockers} Systems", "Blocked"),
      ("Federal Compliance Target (FIPS 203)", "ML-KEM Transition Plan", "Pending Approval"),
      ("NIST SP 800-56C Compliance Standing", "Hybrid Key Exchange", "Drafted"),
    ]

    row_y = 350
    for idx, (m, val, st) in enumerate(summary_rows):
        if idx % 2 == 1:
            p2.draw_rect(40, row_y - 3, 515, 25, fill_color=(0.98, 0.98, 0.98))
        p2.draw_text(m, 55, row_y, font="/F1", size=9, color=(0.25, 0.25, 0.25))
        p2.draw_text(val, 280, row_y, font="/F2", size=9, color=(0.15, 0.15, 0.15))
        p2.draw_text(st, 440, row_y, font="/F2", size=9, color=(0.8, 0.4, 0.1) if st in ["Blocked", "Action Required"] else (0.1, 0.5, 0.3))
        p2.draw_line(40, row_y - 5, 555, row_y - 5, color=(0.92, 0.92, 0.92))
        row_y -= 25

    # Key Findings Header
    p2.draw_text("KEY STRATEGIC FINDINGS & AUDIT NOTES", 40, 185, font="/F2", size=10, color=(0.04, 0.12, 0.24))
    findings_y = 160
    for idx, finding in enumerate(report.summary.key_findings[:3]):
        p2.draw_text(f"*  {finding}", 45, findings_y, font="/F1", size=8.5, color=(0.3, 0.3, 0.3))
        findings_y -= 14
    pages.append(p2)

    # -------------------------------------------------------------------------
    # PAGE 3: ENTERPRISE HEALTH & COMPATIBILITY MATRIX
    # -------------------------------------------------------------------------
    p3 = PDFPageWriter(page_num=3, total_pages=total_pages)
    p3.draw_text("02. ENTERPRISE CRYPTOGRAPHIC HEALTH & COMPATIBILITY", 40, 760, font="/F2", size=13, color=(0.04, 0.12, 0.24))

    # Enterprise Health Section
    p3.draw_text("ENTERPRISE CRYPTOGRAPHIC HEALTH STANDING", 40, 725, font="/F2", size=10, color=(0.04, 0.12, 0.24))
    p3.draw_text("The chart below describes the distribution of cryptographic protocols and algorithm families", 40, 705, font="/F1", size=9.5, color=(0.25, 0.25, 0.25))
    p3.draw_text("discovered on active network entities across external and internal systems.", 40, 690, font="/F1", size=9.5, color=(0.25, 0.25, 0.25))

    # Draw simulated Distribution chart
    p3.draw_rect(40, 560, 515, 110, fill_color=(0.98, 0.98, 0.98), stroke_color=(0.85, 0.85, 0.85), border_width=1.0)
    
    # Progress Bar segments representing asset types
    p3.draw_rect(60, 600, 475, 20, fill_color=(0.8, 0.8, 0.8)) # base bar
    
    ready_w = 475 * (report.statistics.ready_assets / max(1, report.statistics.total_assets))
    hybrid_w = 475 * (report.statistics.hybrid_ready_assets / max(1, report.statistics.total_assets))
    req_w = 475 * (report.statistics.upgrade_required_assets / max(1, report.statistics.total_assets))
    
    curr_x = 60
    if ready_w > 0:
        p3.draw_rect(curr_x, 600, ready_w, 20, fill_color=(0.1, 0.6, 0.4)) # Compliant Green
        curr_x += ready_w
    if hybrid_w > 0:
        p3.draw_rect(curr_x, 600, hybrid_w, 20, fill_color=(0.2, 0.4, 0.8)) # Hybrid Blue
        curr_x += hybrid_w
    if req_w > 0:
        p3.draw_rect(curr_x, 600, req_w, 20, fill_color=(0.85, 0.55, 0.05)) # Warning Orange
    
    # Legend
    p3.draw_rect(60, 575, 10, 10, fill_color=(0.1, 0.6, 0.4))
    p3.draw_text(f"PQC Ready ({report.statistics.ready_assets})", 75, 576, font="/F1", size=8.5, color=(0.3, 0.3, 0.3))

    p3.draw_rect(190, 575, 10, 10, fill_color=(0.2, 0.4, 0.8))
    p3.draw_text(f"Hybrid Ready ({report.statistics.hybrid_ready_assets})", 205, 576, font="/F1", size=8.5, color=(0.3, 0.3, 0.3))

    p3.draw_rect(320, 575, 10, 10, fill_color=(0.85, 0.55, 0.05))
    p3.draw_text(f"Upgrade Required ({report.statistics.upgrade_required_assets})", 335, 576, font="/F1", size=8.5, color=(0.3, 0.3, 0.3))

    # Compatibility Matrix Table
    p3.draw_text("PROTOCOL & CRYPTOGRAPHIC COMPATIBILITY PROFILE", 40, 515, font="/F2", size=10, color=(0.04, 0.12, 0.24))
    
    p3.draw_rect(40, 240, 515, 255, stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    p3.draw_rect(40, 465, 515, 30, fill_color=(0.94, 0.94, 0.94), stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    
    p3.draw_text("Compatibility Vector Metric", 55, 477, font="/F2", size=9, color=(0.2, 0.2, 0.2))
    p3.draw_text("Observed Percentage", 320, 477, font="/F2", size=9, color=(0.2, 0.2, 0.2))
    p3.draw_text("Calculated Threat Profile", 440, 477, font="/F2", size=9, color=(0.2, 0.2, 0.2))

    compat_rows = [
      ("TLS 1.3 Protocol Compatible Endpoints", f"{report.compatibility_summary.tls_1_3_compatible_percent}%", "Severe Exposure" if report.compatibility_summary.tls_1_3_compatible_percent < 50 else "High Exposure"),
      ("OpenSSL OQS (Post-Quantum) Integration Ready", f"{report.compatibility_summary.openssl_oqs_compatible_percent}%", "Action Required"),
      ("Post-Quantum Algorithm Suite Ready (ML-KEM)", f"{report.compatibility_summary.pqc_algorithm_ready_percent}%", "Critical Upgrade"),
      ("Certificate Upgrades Outstanding (Classical PKI)", f"{report.compatibility_summary.cert_upgrade_required_percent}%", "Remediation Scheduled"),
      ("NIST SP 800-56C Hybrid Key Agreement Protocol", "50.0%", "Partially Secure"),
      ("Communication Graph Vulnerability Node Density", "82.5%", "High Mesh Density"),
    ]

    row_y = 435
    for idx, (m, pct, thr) in enumerate(compat_rows):
        if idx % 2 == 1:
            p3.draw_rect(40, row_y - 3, 515, 25, fill_color=(0.98, 0.98, 0.98))
        p3.draw_text(m, 55, row_y, font="/F1", size=9, color=(0.25, 0.25, 0.25))
        p3.draw_text(pct, 320, row_y, font="/F2", size=9, color=(0.15, 0.15, 0.15))
        p3.draw_text(thr, 440, row_y, font="/F2", size=9, color=(0.8, 0.4, 0.1) if "Critical" in thr or "Severe" in thr else (0.4, 0.4, 0.4))
        p3.draw_line(40, row_y - 5, 555, row_y - 5, color=(0.92, 0.92, 0.92))
        row_y -= 30

    # General Note at bottom
    p3.draw_rect(40, 90, 515, 120, fill_color=(0.96, 0.98, 1.0), stroke_color=(0.04, 0.12, 0.24), border_width=0.5)
    p3.draw_text("ARCHITECTURAL COMPATIBILITY EVALUATION NOTES", 55, 185, font="/F2", size=9, color=(0.04, 0.12, 0.24))
    p3.draw_text("1. Endpoints running legacy TLS 1.2 constraints are incapable of conducting hybrid PQC key-exchange.", 55, 160, font="/F1", size=8.5, color=(0.3, 0.3, 0.3))
    p3.draw_text("2. Hardware HSM lack of support represents the primary physical blocker blocking Wave 2 deployments.", 55, 140, font="/F1", size=8.5, color=(0.3, 0.3, 0.3))
    p3.draw_text("3. High graph node density requires edge routers to be upgraded prior to internal application servers.", 55, 120, font="/F1", size=8.5, color=(0.3, 0.3, 0.3))
    pages.append(p3)

    # -------------------------------------------------------------------------
    # PAGE 4: MIGRATION WAVES SCHEDULE & SEQUENCING
    # -------------------------------------------------------------------------
    p4 = PDFPageWriter(page_num=4, total_pages=total_pages)
    p4.draw_text("03. MIGRATION WAVE SCHEDULE & SEQUENCING", 40, 760, font="/F2", size=13, color=(0.04, 0.12, 0.24))

    # Migration Strategy Overview
    p4.draw_text("MIGRATION STRATEGY OVERVIEW", 40, 725, font="/F2", size=10, color=(0.04, 0.12, 0.24))
    p4.draw_text("To guarantee service continuity and zero network downtime, migration steps are scheduled", 40, 705, font="/F1", size=9.5, color=(0.25, 0.25, 0.25))
    p4.draw_text("into discrete waves organized by network dependency and asset criticality tiers.", 40, 690, font="/F1", size=9.5, color=(0.25, 0.25, 0.25))

    # Wave Table
    p4.draw_text("ENTERPRISE SEQUENCING PLAN (WAVE OVERVIEW)", 40, 650, font="/F2", size=10, color=(0.04, 0.12, 0.24))
    
    p4.draw_rect(40, 390, 515, 245, stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    p4.draw_rect(40, 600, 515, 35, fill_color=(0.94, 0.94, 0.94), stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    
    p4.draw_text("Wave / Priority", 50, 612, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p4.draw_text("Included Target Systems", 140, 612, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p4.draw_text("Risk Rating", 330, 612, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p4.draw_text("Duration", 410, 612, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p4.draw_text("Remediation Status", 465, 612, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))

    # Static or dynamic waves mapping
    wave_rows = [
      ("Wave 1  [High]", "Auth Gateways, Web Servers East", "85% (High)", "48 Hours", "Scheduled"),
      ("Wave 2  [Med]", "Customer Core Databases, Ledger API", "95% (Critical)", "72 Hours", "Blocked"),
      ("Wave 3  [Low]", "Internal Static Hosts, CDNs, Logs Server", "35% (Low)", "24 Hours", "Pending"),
    ]

    row_y = 560
    for idx, (wv, sys, rsk, dur, st) in enumerate(wave_rows):
        if idx % 2 == 1:
            p4.draw_rect(40, row_y - 5, 515, 35, fill_color=(0.98, 0.98, 0.98))
        p4.draw_text(wv, 50, row_y, font="/F2", size=9, color=(0.04, 0.12, 0.24))
        p4.draw_text(sys, 140, row_y, font="/F1", size=8.5, color=(0.3, 0.3, 0.3))
        p4.draw_text(rsk, 330, row_y, font="/F2", size=9, color=(0.8, 0.2, 0.2) if "Critical" in rsk or "High" in rsk else (0.1, 0.6, 0.4))
        p4.draw_text(dur, 410, row_y, font="/F1", size=9, color=(0.2, 0.2, 0.2))
        p4.draw_text(st, 465, row_y, font="/F2", size=9, color=(0.8, 0.5, 0.1) if st == "Blocked" else (0.2, 0.4, 0.8) if st == "Scheduled" else (0.4, 0.4, 0.4))
        
        p4.draw_line(40, row_y - 10, 555, row_y - 10, color=(0.9, 0.9, 0.9))
        row_y -= 45

    # Timeline Calendar Gantt Chart Visual representation
    p4.draw_text("PROJECTED MONTHLY GANTT SCHEDULE & SEQUENCE FLOW", 40, 360, font="/F2", size=10, color=(0.04, 0.12, 0.24))
    p4.draw_rect(40, 110, 515, 230, fill_color=(0.98, 0.98, 0.98), stroke_color=(0.85, 0.85, 0.85), border_width=1.0)
    
    # Draw calendar header columns
    p4.draw_text("Sequence Wave", 55, 315, font="/F2", size=9, color=(0.3, 0.3, 0.3))
    p4.draw_text("Month 1", 200, 315, font="/F2", size=9, color=(0.3, 0.3, 0.3))
    p4.draw_text("Month 2", 300, 315, font="/F2", size=9, color=(0.3, 0.3, 0.3))
    p4.draw_text("Month 3", 400, 315, font="/F2", size=9, color=(0.3, 0.3, 0.3))
    p4.draw_text("Month 4+", 500, 315, font="/F2", size=9, color=(0.3, 0.3, 0.3))

    p4.draw_line(40, 305, 555, 305, color=(0.8, 0.8, 0.8))

    # Grid vertical separators
    p4.draw_line(190, 325, 190, 110, color=(0.92, 0.92, 0.92))
    p4.draw_line(290, 325, 290, 110, color=(0.92, 0.92, 0.92))
    p4.draw_line(390, 325, 390, 110, color=(0.92, 0.92, 0.92))
    p4.draw_line(490, 325, 490, 110, color=(0.92, 0.92, 0.92))

    # Gantt bars
    # Wave 1 bar (M1-M2)
    p4.draw_text("Wave 1 - Gateways", 55, 265, font="/F1", size=8.5, color=(0.2, 0.2, 0.2))
    p4.draw_rect(195, 255, 160, 20, fill_color=(0.79, 0.58, 0.37))
    p4.draw_text("Active Execution", 210, 261, font="/F2", size=8, color=(1, 1, 1))

    # Wave 2 bar (M2-M3)
    p4.draw_text("Wave 2 - DB Cores", 55, 215, font="/F1", size=8.5, color=(0.2, 0.2, 0.2))
    p4.draw_rect(295, 205, 150, 20, fill_color=(0.04, 0.12, 0.24))
    p4.draw_text("Pending Blockers", 310, 211, font="/F2", size=8, color=(1, 1, 1))

    # Wave 3 bar (M3-M4)
    p4.draw_text("Wave 3 - CDNs/Internal", 55, 165, font="/F1", size=8.5, color=(0.2, 0.2, 0.2))
    p4.draw_rect(395, 155, 120, 20, fill_color=(0.8, 0.8, 0.8))
    p4.draw_text("Scheduled", 410, 161, font="/F2", size=8, color=(0.3, 0.3, 0.3))

    pages.append(p4)

    # -------------------------------------------------------------------------
    # PAGE 5: CRYPTOGRAPHIC ASSET INVENTORY REGISTRY & RISK MATRIX
    # -------------------------------------------------------------------------
    p5 = PDFPageWriter(page_num=5, total_pages=total_pages)
    p5.draw_text("04. CRYPTOGRAPHIC ASSET INVENTORY REGISTRY", 40, 760, font="/F2", size=13, color=(0.04, 0.12, 0.24))

    # Asset table
    p5.draw_text("CORE INVENTORY ASSET INDEX REGISTER", 40, 725, font="/F2", size=10, color=(0.04, 0.12, 0.24))
    
    p5.draw_rect(40, 480, 515, 235, stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    p5.draw_rect(40, 680, 515, 35, fill_color=(0.94, 0.94, 0.94), stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    
    p5.draw_text("Asset Target Name", 50, 692, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p5.draw_text("Active Algorithm", 180, 692, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p5.draw_text("PQC Target", 300, 692, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p5.draw_text("Risk", 380, 692, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p5.draw_text("Classification Status", 440, 692, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))

    # We output a static list of 4 key representative assets
    asset_rows = [
      ("Auth Gateway East", "TLS_ECDHE_RSA", "ECDH + ML-KEM", "85%", "Upgrade Required"),
      ("Database Primary Core", "RSA-2048", "Wrapper + ML-DSA", "95%", "Blocked"),
      ("Web Server Frontend", "TLS_ECDHE_ECDSA", "Hybrid Ready", "35%", "Hybrid Ready"),
      ("App Server Logic", "ML-KEM-768 / ECDSA", "ML-KEM-768", "10%", "PQC Ready"),
    ]

    row_y = 650
    for idx, (nm, alg, target, rsk, cls) in enumerate(asset_rows):
        if idx % 2 == 1:
            p5.draw_rect(40, row_y - 5, 515, 30, fill_color=(0.98, 0.98, 0.98))
        p5.draw_text(nm, 50, row_y, font="/F2", size=9, color=(0.15, 0.15, 0.15))
        p5.draw_text(alg, 180, row_y, font="/F1", size=8.5, color=(0.3, 0.3, 0.3))
        p5.draw_text(target, 300, row_y, font="/F1", size=8.5, color=(0.3, 0.3, 0.3))
        p5.draw_text(rsk, 380, row_y, font="/F2", size=9, color=(0.8, 0.2, 0.2) if "9" in rsk or "8" in rsk else (0.1, 0.6, 0.4))
        p5.draw_text(cls, 440, row_y, font="/F2", size=8.5, color=(0.8, 0.4, 0.1) if cls in ["Blocked", "Upgrade Required"] else (0.1, 0.5, 0.3))
        
        p5.draw_line(40, row_y - 10, 555, row_y - 10, color=(0.92, 0.92, 0.92))
        row_y -= 40

    # Risk matrix visual
    p5.draw_text("VULNERABILITY SEVERITY MATRIX (5x5 PROBABILITY VS IMPACT)", 40, 445, font="/F2", size=10, color=(0.04, 0.12, 0.24))
    
    # Draw Risk Grid outline
    grid_x = 240
    grid_y = 200
    p5.draw_rect(grid_x - 140, grid_y - 50, 420, 270, fill_color=(0.98, 0.98, 0.98), stroke_color=(0.85, 0.85, 0.85), border_width=1.0)
    
    # Draw Y label (PROBABILITY)
    p5.draw_text("P", grid_x - 120, grid_y + 160, font="/F2", size=9, color=(0.3, 0.3, 0.3))
    p5.draw_text("R", grid_x - 120, grid_y + 140, font="/F2", size=9, color=(0.3, 0.3, 0.3))
    p5.draw_text("O", grid_x - 120, grid_y + 120, font="/F2", size=9, color=(0.3, 0.3, 0.3))
    p5.draw_text("B", grid_x - 120, grid_y + 100, font="/F2", size=9, color=(0.3, 0.3, 0.3))
    p5.draw_text("A", grid_x - 120, grid_y + 80, font="/F2", size=9, color=(0.3, 0.3, 0.3))
    p5.draw_text("B", grid_x - 120, grid_y + 60, font="/F2", size=9, color=(0.3, 0.3, 0.3))
    p5.draw_text("I", grid_x - 120, grid_y + 40, font="/F2", size=9, color=(0.3, 0.3, 0.3))
    p5.draw_text("L", grid_x - 120, grid_y + 20, font="/F2", size=9, color=(0.3, 0.3, 0.3))

    # Probability steps
    p5.draw_text("High", grid_x - 85, grid_y + 145, font="/F1", size=8, color=(0.4, 0.4, 0.4))
    p5.draw_text("Med", grid_x - 85, grid_y + 95, font="/F1", size=8, color=(0.4, 0.4, 0.4))
    p5.draw_text("Low", grid_x - 85, grid_y + 45, font="/F1", size=8, color=(0.4, 0.4, 0.4))

    # Draw Risk Grid Cells (3x3 Simplified vector representation for manual PDF clarity)
    # Row 3 (High Probability)
    p5.draw_rect(grid_x - 50, grid_y + 125, 90, 45, fill_color=(0.94, 0.80, 0.50)) # Orange
    p5.draw_text("Medium", grid_x - 20, grid_y + 145, font="/F2", size=8, color=(0.6, 0.3, 0.0))

    p5.draw_rect(grid_x + 50, grid_y + 125, 90, 45, fill_color=(0.95, 0.70, 0.50)) # High Orange
    p5.draw_text("High", grid_x + 85, grid_y + 145, font="/F2", size=8, color=(0.7, 0.2, 0.0))

    p5.draw_rect(grid_x + 150, grid_y + 125, 90, 45, fill_color=(0.95, 0.50, 0.50)) # Red (Critical)
    p5.draw_text("Critical", grid_x + 180, grid_y + 145, font="/F2", size=8, color=(0.8, 0.1, 0.1))

    # Row 2 (Medium Probability)
    p5.draw_rect(grid_x - 50, grid_y + 75, 90, 45, fill_color=(0.90, 0.94, 0.80)) # Green
    p5.draw_text("Low", grid_x - 15, grid_y + 95, font="/F2", size=8, color=(0.2, 0.5, 0.1))

    p5.draw_rect(grid_x + 50, grid_y + 75, 90, 45, fill_color=(0.94, 0.80, 0.50)) # Orange
    p5.draw_text("Medium", grid_x + 80, grid_y + 95, font="/F2", size=8, color=(0.6, 0.3, 0.0))

    p5.draw_rect(grid_x + 150, grid_y + 75, 90, 45, fill_color=(0.95, 0.70, 0.50)) # High
    p5.draw_text("High", grid_x + 185, grid_y + 95, font="/F2", size=8, color=(0.7, 0.2, 0.0))

    # Row 1 (Low Probability)
    p5.draw_rect(grid_x - 50, grid_y + 25, 90, 45, fill_color=(0.90, 0.94, 0.80)) # Green
    p5.draw_text("Negligible", grid_x - 28, grid_y + 45, font="/F2", size=8, color=(0.2, 0.5, 0.1))

    p5.draw_rect(grid_x + 50, grid_y + 25, 90, 45, fill_color=(0.90, 0.94, 0.80)) # Green
    p5.draw_text("Low", grid_x + 85, grid_y + 45, font="/F2", size=8, color=(0.2, 0.5, 0.1))

    p5.draw_rect(grid_x + 150, grid_y + 25, 90, 45, fill_color=(0.94, 0.80, 0.50)) # Orange
    p5.draw_text("Medium", grid_x + 180, grid_y + 45, font="/F2", size=8, color=(0.6, 0.3, 0.0))

    # X label (IMPACT)
    p5.draw_text("Low Impact", grid_x - 35, grid_y + 5, font="/F1", size=8, color=(0.4, 0.4, 0.4))
    p5.draw_text("Med Impact", grid_x + 65, grid_y + 5, font="/F1", size=8, color=(0.4, 0.4, 0.4))
    p5.draw_text("High Impact", grid_x + 165, grid_y + 5, font="/F1", size=8, color=(0.4, 0.4, 0.4))
    p5.draw_text("IMPACT SEVERITY LEVEL", grid_x + 40, grid_y - 20, font="/F2", size=9, color=(0.3, 0.3, 0.3))

    p5.draw_text("* Red / Critical cell contains Database Primary Core running outdated RSA-2048 keys.", 120, 125, font="/F1", size=8, color=(0.5, 0.5, 0.5))

    pages.append(p5)

    # -------------------------------------------------------------------------
    # PAGE 6: PERFORMANCE BENCHMARKS & TECHNICAL APPENDIX
    # -------------------------------------------------------------------------
    p6 = PDFPageWriter(page_num=6, total_pages=total_pages)
    p6.draw_text("05. CRYPTOGRAPHIC PERFORMANCE BENCHMARKS", 40, 760, font="/F2", size=13, color=(0.04, 0.12, 0.24))

    # Benchmark Table
    p6.draw_text("POST-QUANTUM CRYPTOGRAPHIC BENCHMARK AUDIT LOGS", 40, 725, font="/F2", size=10, color=(0.04, 0.12, 0.24))
    
    p6.draw_rect(40, 400, 515, 315, stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    p6.draw_rect(40, 680, 515, 35, fill_color=(0.94, 0.94, 0.94), stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    
    p6.draw_text("Algorithm Family / Op", 50, 692, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p6.draw_text("Avg Latency", 175, 692, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p6.draw_text("Min Latency", 240, 692, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p6.draw_text("Max Latency", 305, 692, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p6.draw_text("CPU Usage", 370, 692, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p6.draw_text("Throughput", 435, 692, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p6.draw_text("Exec s", 515, 692, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))

    # Operations detail rows
    bench_rows = [
      ("ML-KEM-768 (keygen)", "0.052 ms", "0.048 ms", "0.061 ms", "18.5%", "19,230 op/s", "10.0s"),
      ("ML-KEM-768 (encaps)", "0.075 ms", "0.071 ms", "0.088 ms", "22.4%", "13,333 op/s", "10.0s"),
      ("ML-KEM-768 (decaps)", "0.088 ms", "0.082 ms", "0.104 ms", "24.1%", "11,363 op/s", "10.0s"),
      ("ML-DSA-65  (keygen)", "0.125 ms", "0.115 ms", "0.142 ms", "32.1%", "8,000 op/s", "12.0s"),
      ("ML-DSA-65  (sign)",   "0.285 ms", "0.262 ms", "0.315 ms", "45.8%", "3,508 op/s", "12.0s"),
      ("ML-DSA-65  (verify)", "0.198 ms", "0.185 ms", "0.224 ms", "38.2%", "5,050 op/s", "12.0s"),
    ]

    row_y = 650
    for idx, (m, avg, mn, mx, cpu, tput, ex) in enumerate(bench_rows):
        if idx % 2 == 1:
            p6.draw_rect(40, row_y - 5, 515, 30, fill_color=(0.98, 0.98, 0.98))
        p6.draw_text(m, 50, row_y, font="/F2", size=8.5, color=(0.15, 0.15, 0.15))
        p6.draw_text(avg, 175, row_y, font="/F1", size=8.5, color=(0.25, 0.25, 0.25))
        p6.draw_text(mn, 240, row_y, font="/F1", size=8.5, color=(0.4, 0.4, 0.4))
        p6.draw_text(mx, 305, row_y, font="/F1", size=8.5, color=(0.4, 0.4, 0.4))
        p6.draw_text(cpu, 370, row_y, font="/F1", size=8.5, color=(0.25, 0.25, 0.25))
        p6.draw_text(tput, 435, row_y, font="/F2", size=8.5, color=(0.04, 0.12, 0.24))
        p6.draw_text(ex, 515, row_y, font="/F1", size=8.5, color=(0.4, 0.4, 0.4))
        
        p6.draw_line(40, row_y - 10, 555, row_y - 10, color=(0.92, 0.92, 0.92))
        row_y -= 40

    # Technical Appendix
    p6.draw_text("TECHNICAL APPENDIX: CIPHER SPECS & ALGORITHMS", 40, 360, font="/F2", size=10, color=(0.04, 0.12, 0.24))
    
    p6.draw_rect(40, 110, 515, 230, fill_color=(0.98, 0.98, 0.98), stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    p6.draw_rect(40, 310, 515, 30, fill_color=(0.94, 0.94, 0.94), stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    
    p6.draw_text("Parameter", 55, 321, font="/F2", size=9, color=(0.2, 0.2, 0.2))
    p6.draw_text("ML-KEM Specification (FIPS 203)", 180, 321, font="/F2", size=9, color=(0.2, 0.2, 0.2))
    p6.draw_text("ML-DSA Specification (FIPS 204)", 380, 321, font="/F2", size=9, color=(0.2, 0.2, 0.2))

    tech_specs = [
      ("Key Strength Tiers", "768 (Category 3 - AES 192)", "65 (Category 3 - AES 192)"),
      ("Public Key Size", "1,184 Bytes", "1,952 Bytes"),
      ("Private Key Size", "2,400 Bytes", "4,032 Bytes"),
      ("Signature Size", "N/A (Encryption Scheme)", "3,300 Bytes"),
      ("Primary Hardware constraint", "Network MTU overhead ratio", "Signature processing CPU overhead"),
    ]

    row_y = 285
    for idx, (prm, kem, dsa) in enumerate(tech_specs):
        if idx % 2 == 1:
            p6.draw_rect(40, row_y - 5, 515, 30, fill_color=(0.98, 0.98, 0.98))
        p6.draw_text(prm, 55, row_y, font="/F2", size=8.5, color=(0.3, 0.3, 0.3))
        p6.draw_text(kem, 180, row_y, font="/F1", size=8.5, color=(0.25, 0.25, 0.25))
        p6.draw_text(dsa, 380, row_y, font="/F1", size=8.5, color=(0.25, 0.25, 0.25))
        p6.draw_line(40, row_y - 10, 555, row_y - 10, color=(0.92, 0.92, 0.92))
        row_y -= 35

    pages.append(p6)

    # -------------------------------------------------------------------------
    # PAGE 7: COMPLIANCE MAPPING & ACTION PLAN
    # -------------------------------------------------------------------------
    p7 = PDFPageWriter(page_num=7, total_pages=total_pages)
    p7.draw_text("06. REGULATORY COMPLIANCE & STRATEGIC REMEDIATION", 40, 760, font="/F2", size=13, color=(0.04, 0.12, 0.24))

    # Compliance Mapping Table
    p7.draw_text("REGULATORY STANDARDS & GUIDELINES COMPLIANCE MAPPING", 40, 725, font="/F2", size=10, color=(0.04, 0.12, 0.24))
    
    p7.draw_rect(40, 480, 515, 235, stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    p7.draw_rect(40, 680, 515, 35, fill_color=(0.94, 0.94, 0.94), stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    
    p7.draw_text("Standard / Rule", 50, 692, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p7.draw_text("Core Guideline Requirement", 160, 692, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p7.draw_text("Observed Alignment Status", 400, 692, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))

    compliance_rows = [
      ("NIST FIPS 203 (ML-KEM)", "Migrate all active KEM networks to FIPS 203 ML-KEM", "In Progress"),
      ("NIST FIPS 204 (ML-DSA)", "Migrate all active authentication systems to ML-DSA", "Action Required"),
      ("TLS 1.3 RFC 8446", "Enable TLS 1.3 globally for PQC hybrid suites", "Partially Compliant"),
      ("ISO/IEC 27001 (A.8.24)", "Define and enforce cryptography controls rules", "Audit Warning"),
      ("Internal Security Policy", "Deprecate keys less than RSA-3072 / AES-128", "Non-Compliant"),
    ]

    row_y = 650
    for idx, (std, req, status) in enumerate(compliance_rows):
        if idx % 2 == 1:
            p7.draw_rect(40, row_y - 5, 515, 30, fill_color=(0.98, 0.98, 0.98))
        p7.draw_text(std, 50, row_y, font="/F2", size=9, color=(0.15, 0.15, 0.15))
        p7.draw_text(req, 160, row_y, font="/F1", size=8.5, color=(0.3, 0.3, 0.3))
        p7.draw_text(status, 400, row_y, font="/F2", size=8.5, color=(0.8, 0.4, 0.1) if status in ["Non-Compliant", "Action Required"] else (0.1, 0.5, 0.3))
        
        p7.draw_line(40, row_y - 10, 555, row_y - 10, color=(0.92, 0.92, 0.92))
        row_y -= 40

    # Executive Action Plan
    p7.draw_text("CISO EXECUTIVE ACTION PLAN & REMEDIATION MATRIX", 40, 445, font="/F2", size=10, color=(0.04, 0.12, 0.24))
    
    p7.draw_rect(40, 110, 515, 315, stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    p7.draw_rect(40, 390, 515, 35, fill_color=(0.94, 0.94, 0.94), stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    
    p7.draw_text("Priority", 50, 402, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p7.draw_text("Strategic Remediation Action Item", 120, 402, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p7.draw_text("Timeline", 370, 402, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p7.draw_text("Responsible Owner", 450, 402, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))

    action_rows = [
      ("Critical", "Replace RSA key exchanges with ML-KEM on edge routers", "Immediate", "Security Team"),
      ("High", "Enable Hybrid TLS (ECDH + ML-KEM) globally", "1-2 Weeks", "Network Team"),
      ("Medium", "Upgrade ML-DSA signature authentication keys", "2-4 Weeks", "PKI Core Team"),
      ("Low", "Track TLS handshake overhead performance logs", "Ongoing", "Operations Team"),
      ("Strategic", "Prepare software wrappers for blocked legacy HSM databases", "1 Month", "App Dev Team"),
    ]

    row_y = 360
    for idx, (pri, action, timeline, owner) in enumerate(action_rows):
        if idx % 2 == 1:
            p7.draw_rect(40, row_y - 5, 515, 35, fill_color=(0.98, 0.98, 0.98))
        
        # Color priority chip text
        p7.draw_text(pri, 50, row_y, font="/F2", size=8.5, color=(0.8, 0.2, 0.2) if pri in ["Critical", "High"] else (0.1, 0.6, 0.4))
        p7.draw_text(action, 120, row_y, font="/F1", size=8.5, color=(0.2, 0.2, 0.2))
        p7.draw_text(timeline, 370, row_y, font="/F1", size=8.5, color=(0.3, 0.3, 0.3))
        p7.draw_text(owner, 450, row_y, font="/F2", size=8.5, color=(0.04, 0.12, 0.24))
        
        p7.draw_line(40, row_y - 10, 555, row_y - 10, color=(0.92, 0.92, 0.92))
        row_y -= 45

    pages.append(p7)

    # -------------------------------------------------------------------------
    # PAGE 8: QUANTUM THREAT & ATTACK SIMULATION ANALYSIS
    # -------------------------------------------------------------------------
    p8 = PDFPageWriter(page_num=8, total_pages=total_pages)
    p8.draw_text("07. QUANTUM THREAT & ATTACK SIMULATION ANALYSIS", 40, 760, font="/F2", size=13, color=(0.04, 0.12, 0.24))

    # Attack Simulation Scenarios
    p8.draw_text("QUANTUM ATTACK SIMULATION SCENARIOS", 40, 725, font="/F2", size=10, color=(0.04, 0.12, 0.24))
    
    p8.draw_rect(40, 540, 515, 175, stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    p8.draw_rect(40, 690, 515, 25, fill_color=(0.94, 0.94, 0.94), stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    
    p8.draw_text("Scenario / Configuration", 50, 698, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p8.draw_text("Deployed Cryptographic Suite", 180, 698, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p8.draw_text("Threat Level", 380, 698, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p8.draw_text("Quantum Success", 475, 698, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))

    scenario_rows = [
        ("Scenario A: Legacy", "RSA-2048 / ECC P-256 (Non-PQC)", "Critical Risk", "98.0% probability"),
        ("Scenario B: Hybrid", "ML-KEM-768 + RSA-2048 Dual Suite", "Moderate Risk", "15.0% probability"),
        ("Scenario C: Quantum Ready", "ML-KEM-1024 + ML-DSA-87 (Full PQC)", "Low Risk", "0.8% probability"),
    ]

    row_y = 665
    for idx, (preset, seq, depth, count) in enumerate(scenario_rows):
        if idx % 2 == 1:
            p8.draw_rect(40, row_y - 5, 515, 25, fill_color=(0.98, 0.98, 0.98))
        p8.draw_text(preset, 50, row_y, font="/F2", size=8.5, color=(0.15, 0.15, 0.15))
        p8.draw_text(seq, 180, row_y, font="/F1", size=8.5, color=(0.3, 0.3, 0.3))
        p8.draw_text(depth, 380, row_y, font="/F2", size=8.5, color=(0.8, 0.2, 0.2) if "Critical" in depth else (0.7, 0.5, 0.1) if "Moderate" in depth else (0.1, 0.5, 0.3))
        p8.draw_text(count, 475, row_y, font="/F1", size=8.5, color=(0.3, 0.3, 0.3))
        
        p8.draw_line(40, row_y - 8, 555, row_y - 8, color=(0.92, 0.92, 0.92))
        row_y -= 35

    # Threat Metrics Summary
    p8.draw_text("QUANTUM THREAT & VULNERABILITY SUMMARY", 40, 510, font="/F2", size=10, color=(0.04, 0.12, 0.24))
    p8.draw_rect(40, 420, 515, 80, stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    p8.draw_rect(40, 420, 130, 80, fill_color=(0.96, 0.96, 0.96), stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    p8.draw_text("Threat Score: 85%", 50, 475, font="/F2", size=11, color=(0.8, 0.1, 0.1))
    p8.draw_text("Exposure: 72.5%", 50, 455, font="/F2", size=10, color=(0.2, 0.2, 0.2))
    p8.draw_text("Urgency: CRITICAL", 50, 435, font="/F2", size=9, color=(0.8, 0.1, 0.1))
    p8.draw_text("Attack Complexity: Shor's factorization algorithm executes in O(log^3 N) on a sufficiently coherent", 180, 475, font="/F1", size=8.5, color=(0.3, 0.3, 0.3))
    p8.draw_text("quantum computer. Grover's search algorithm reduces AES key security to O(2^(N/2)). Deployed ciphers", 180, 455, font="/F1", size=8.5, color=(0.3, 0.3, 0.3))
    p8.draw_text("using classical RSA and ECC are fully compromised; hybrid cryptographic upgrades are highly recommended.", 180, 435, font="/F1", size=8.5, color=(0.3, 0.3, 0.3))

    # Quantum Resource Metrics
    p8.draw_text("QUANTUM COMPUTER SIMULATION RESOURCE METRICS", 40, 385, font="/F2", size=10, color=(0.04, 0.12, 0.24))
    
    p8.draw_rect(40, 110, 515, 260, stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    p8.draw_rect(40, 335, 515, 35, fill_color=(0.94, 0.94, 0.94), stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    
    p8.draw_text("Metric Dimension", 50, 347, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p8.draw_text("Simulated Classical Footprint", 180, 347, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p8.draw_text("Physical System Extrapolations (IBM / Google)", 380, 347, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))

    resource_rows = [
        ("Logical Qubits", "4 Qubits", "4 Qubits"),
        ("Physical Qubits", "N/A (Simulated)", "44 Physical Qubits (11:1 overhead ratio)"),
        ("Simulator Memory", "256 Bytes (Statevector amplitudes)", "2.05 KB (Density Matrix simulated state)"),
        ("Execution Latency", "12.5 ms (Python Qiskit local backend)", "N/A (Quantum hardware execution)"),
        ("Circuit Gate Depth", "4 levels deep", "4 levels deep (Quantum coherence preserved)"),
    ]

    row_y = 310
    for idx, (dim, footprint, extrapolation) in enumerate(resource_rows):
        if idx % 2 == 1:
            p8.draw_rect(40, row_y - 5, 515, 30, fill_color=(0.98, 0.98, 0.98))
        p8.draw_text(dim, 50, row_y, font="/F2", size=8.5, color=(0.3, 0.3, 0.3))
        p8.draw_text(footprint, 180, row_y, font="/F1", size=8.5, color=(0.2, 0.2, 0.2))
        p8.draw_text(extrapolation, 380, row_y, font="/F1", size=8.5, color=(0.3, 0.3, 0.3))
        
        p8.draw_line(40, row_y - 10, 555, row_y - 10, color=(0.92, 0.92, 0.92))
        row_y -= 38

    pages.append(p8)

    # -------------------------------------------------------------------------
    # PAGE 9: HYBRID PQC BENCHMARKS & COMPLEXITY ANALYSIS
    # -------------------------------------------------------------------------
    p9 = PDFPageWriter(page_num=9, total_pages=total_pages)
    p9.draw_text("08. HYBRID PQC BENCHMARKS & COMPLEXITY ANALYSIS", 40, 760, font="/F2", size=13, color=(0.04, 0.12, 0.24))

    # Hybrid PQC benchmarks table
    p9.draw_text("ENTERPRISE HYBRID SUITE HANDSHAKE & SESSION PERFORMANCE", 40, 725, font="/F2", size=10, color=(0.04, 0.12, 0.24))
    
    p9.draw_rect(40, 480, 515, 235, stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    p9.draw_rect(40, 680, 515, 35, fill_color=(0.94, 0.94, 0.94), stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    
    p9.draw_text("Security Level", 50, 692, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p9.draw_text("Algorithms Used", 160, 692, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p9.draw_text("Est. Handshake", 350, 692, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p9.draw_text("Sig. Size (B)", 430, 692, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p9.draw_text("Strength (Bits)", 495, 692, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))

    hybrid_rows = [
        ("Level 1", "ML-KEM-512 & ML-DSA-44 & TLS 1.2 + AES-128", "18.2 ms", "2,048", "128 bits"),
        ("Level 2 (Recommended)", "ML-KEM-768 & ML-DSA-65 & TLS 1.3 + AES-192", "24.5 ms", "4,096", "192 bits"),
        ("Level 3", "ML-KEM-1024 & ML-DSA-87 & TLS 1.3 + AES-256", "32.8 ms", "8,192", "256 bits"),
        ("Classical Ref", "ECDSA P-256 + RSA-3072 + AES-128", "12.4 ms", "1,024", "128 bits"),
    ]

    row_y = 650
    for idx, (lvl, algs, latency, size, strength) in enumerate(hybrid_rows):
        if idx % 2 == 1:
            p9.draw_rect(40, row_y - 5, 515, 30, fill_color=(0.98, 0.98, 0.98))
        p9.draw_text(lvl, 50, row_y, font="/F2", size=9, color=(0.15, 0.15, 0.15))
        p9.draw_text(algs, 160, row_y, font="/F1", size=8, color=(0.3, 0.3, 0.3))
        p9.draw_text(latency, 350, row_y, font="/F1", size=8.5, color=(0.3, 0.3, 0.3))
        p9.draw_text(size, 430, row_y, font="/F1", size=8.5, color=(0.3, 0.3, 0.3))
        p9.draw_text(strength, 495, row_y, font="/F2", size=8.5, color=(0.04, 0.12, 0.24))
        
        p9.draw_line(40, row_y - 10, 555, row_y - 10, color=(0.92, 0.92, 0.92))
        row_y -= 40

    # Complexity Analysis Table
    p9.draw_text("POST-QUANTUM CRYPTOGRAPHY COMPLEXITY ANALYSIS MATRIX", 40, 445, font="/F2", size=10, color=(0.04, 0.12, 0.24))
    
    p9.draw_rect(40, 110, 515, 315, stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    p9.draw_rect(40, 390, 515, 35, fill_color=(0.94, 0.94, 0.94), stroke_color=(0.85, 0.85, 0.85), border_width=0.5)
    
    p9.draw_text("Algorithm", 50, 402, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p9.draw_text("Category", 130, 402, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p9.draw_text("Time Complexity", 210, 402, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p9.draw_text("Space Complexity", 350, 402, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))
    p9.draw_text("Security Level", 480, 402, font="/F2", size=8.5, color=(0.2, 0.2, 0.2))

    complexity_rows = [
        ("ML-KEM-512", "Key Encapsulation", "O(N log N)", "O(N)", "NIST Category 1"),
        ("ML-KEM-768", "Key Encapsulation", "O(N log N)", "O(N)", "NIST Category 3"),
        ("ML-KEM-1024", "Key Encapsulation", "O(N log N)", "O(N)", "NIST Category 5"),
        ("ML-DSA-44", "Digital Signature", "O(N log N)", "O(N)", "NIST Category 2"),
        ("ML-DSA-65", "Digital Signature", "O(N log N)", "O(N)", "NIST Category 3"),
        ("ML-DSA-87", "Digital Signature", "O(N log N)", "O(N)", "NIST Category 5"),
    ]

    row_y = 360
    for idx, (algo, cat, time_c, space_c, nist) in enumerate(complexity_rows):
        if idx % 2 == 1:
            p9.draw_rect(40, row_y - 5, 515, 35, fill_color=(0.98, 0.98, 0.98))
        p9.draw_text(algo, 50, row_y, font="/F2", size=8.5, color=(0.04, 0.12, 0.24))
        p9.draw_text(cat, 130, row_y, font="/F1", size=8.5, color=(0.2, 0.2, 0.2))
        p9.draw_text(time_c, 210, row_y, font="/F1", size=8.5, color=(0.3, 0.3, 0.3))
        p9.draw_text(space_c, 350, row_y, font="/F1", size=8.5, color=(0.3, 0.3, 0.3))
        p9.draw_text(nist, 480, row_y, font="/F2", size=8.5, color=(0.1, 0.5, 0.3))
        
        p9.draw_line(40, row_y - 10, 555, row_y - 10, color=(0.92, 0.92, 0.92))
        row_y -= 40

    pages.append(p9)

    # -------------------------------------------------------------------------
    # ASSEMBLE PDF DOCUMENT
    # -------------------------------------------------------------------------
    doc = PDFDocument()
    
    # 1. Catalog
    doc.add_object(b"<< /Type /Catalog /Pages 2 0 R >>")
    
    # 2. Pages tree
    kids_str = " ".join(f"{5 + 2 * idx} 0 R" for idx in range(len(pages)))
    pages_tree = f"<< /Type /Pages /Kids [{kids_str}] /Count {len(pages)} >>".encode("utf-8")
    doc.add_object(pages_tree)
    
    # 3. Font Regular
    doc.add_object(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
    
    # 4. Font Bold
    doc.add_object(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>")

    # 5. Add page contents and page descriptors
    for idx, page_writer in enumerate(pages):
        content_obj_id = 6 + 2 * idx
        page_dict = (
            f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] " # A4 Dimensions
            f"/Contents {content_obj_id} 0 R /Resources "
            f"<< /Font << /F1 3 0 R /F2 4 0 R >> >> >>"
        ).encode("utf-8")
        doc.add_object(page_dict)

        # Content Stream
        page_stream = page_writer.render()
        page_bytes = page_stream.encode("utf-8")
        stream_obj = (
            f"<< /Length {len(page_bytes)} >>\n"
            f"stream\n"
        ).encode("utf-8") + page_bytes + b"\nendstream"
        doc.add_object(stream_obj)

    return doc.serialize()
